### ISSUE TITLE
graph generation gives error

### ISSUE THREAD

**Issue by coolnitin157** [superluminalengineering/superluminal-react-example#1]
@nielsandriesse I am trying to use latest 1.0.7 superluminal with react, I have used the sample code given it worked for text data, but as soon as I asked it to generate a graph data. it started to show some issue related to assitantview

as follows 

   ```
 Uncaught runtime errors:
×
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `AssistantView`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `AssistantView`.
    at createFiberFromTypeAndProps (http://localhost:4000/static/js/bundle.js:287593:21)
    at createFiberFromElement (http://localhost:4000/static/js/bundle.js:287614:19)
    at reconcileSingleElement (http://localhost:4000/static/js/bundle.js:276705:27)
    at reconcileChildFibers (http://localhost:4000/static/js/bundle.js:276755:39)
    at reconcileChildren (http://localhost:4000/static/js/bundle.js:279697:32)
    at updateHostComponent (http://localhost:4000/static/js/bundle.js:280341:7)
    at beginWork (http://localhost:4000/static/js/bundle.js:281786:18)
    at HTMLUnknownElement.callCallback (http://localhost:4000/static/js/bundle.js:266772:18)
    at Object.invokeGuardedCallbackDev (http://localhost:4000/static/js/bundle.js:266816:20)
    at invokeGuardedCallback (http://localhost:4000/static/js/bundle.js:266873:35)
```
    as per my analysis, it generate code for graph the issue is somewhere in rendering it chat area.
![Superluminal-React-Example](https://github.com/superluminalengineering/superluminal-react-example/assets/39884004/4e9cc787-36ca-423a-97eb-619f00701a5f)

even I tried using old packages 1.0.0 and 1.0.2 but with those version, it was not even initializing the chat properly and stuck in between.

**Comment by coolnitin157** [comment]
I fixed it using 
import React from "react";
// import Plot from "react-plotly.js";
import Plotly from "plotly.js-basic-dist";

import createPlotlyComponent from "react-plotly.js/factory";
const Plot = createPlotlyComponent(Plotly);
